---
# tasks file for db

- name: Install MySQL
  apt:
    name: ["mysql-server", "mysql-client", "python3-pymysql"]
    state: latest
  notify: restart mysql

# Configurations

- name: Setup root password
  mysql_user:
    name: root
    password: "{{ db_pass }}"
    login_unix_socket: /var/run/mysqld/mysqld.sock

- name: Removes all anonymous user accounts
  mysql_user:
    name: ""
    host_all: yes
    state: absent
    login_user: root
    login_password: "{{ db_pass }}"

- name: Removes the MySQL test database
  mysql_db:
    name: test
    state: absent
    login_user: root
    login_password: "{{ db_pass }}"

- name: Create database
  mysql_db:
    name: "{{ db_name }}"
    state: present
    login_user: root
    login_password: "{{ db_pass }}"
# - name: Create user for the database
#   mysql_user:
#     name: "{{ db_user }}"
#     password: "{{ db_pass }}"
#     encrypted: yes
#     priv: "{{ db_name }}.*:ALL"
#     state: present
